version: '3.4'

services:
  redis:
    container_name: kvstore-redis
    image: "redis:7-alpine"
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DATABASES: 1
    expose:
      - ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis_data:/root/redis
      